name: Daily archive

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Zip text
        run: cd out && zip -r9 "../archive-${{ steps.date.outputs.date }}.zip" .

      - name: Upload text
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: archive-${{ steps.date.outputs.date }}
          prerelease: false
          files: archive-${{ steps.date.outputs.date }}.zip

      - name: Zip ebooks
        run: cd out_ebooks && zip -r9 "../archive-ebooks-${{ steps.date.outputs.date }}.zip" .

      - name: Upload ebooks
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: archive-ebooks-${{ steps.date.outputs.date }}
          prerelease: false
          files: archive-ebooks-${{ steps.date.outputs.date }}.zip
