name: Update archive

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3

      - name: Install modules
        run: pip install praw

      - name: Scrape
        env:
          REDDIT_ID: ${{ secrets.REDDIT_ID }}
          REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
        run: python main.py

      - name: Index
        run: |
          dart pub global activate inc
          inc -i index.base.md -o index.md

      - name: Generate ebooks
        run: |
          sudo apt-get install pandoc
          bash util/gen_ebooks.sh

      - name: Push
        run: |
          git config --global user.email "yessleep@github-action-yessleep.com"
          git config --global user.name "yessleep-github-action"
          git add .
          git commit -sam "Updated r/nosleep stories" || true
          git push || true
